blog/urls.py
from django.urls import path

from .views import blog_detail, blog_list

app_name = 'blog'

urlpatterns = [
    path('list/', blog_list, name='list'),
    path('detail/<int:year>/<int:month>/<int:day>/<slug:slug>/', blog_detail, name='detail'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('contact/', include('contact.urls', namespace='contact')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from .views import contact

app_name = 'contact'

urlpatterns = [
    path('', contact, name='contact'),
]

main/urls.py
from django.urls import path
from .views import home, about

app_name = 'main'

urlpatterns = [
    path('', home, name='home'),
    path('about/', about, name='about'),
]

blog/models.py
from django.db import models
from django.shortcuts import redirect
from django.urls import reverse
from django.db.models.signals import pre_save
from profiles.models import Profile
from django.utils.text import slugify


class Category(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Tag(models.Model):
    title = models.CharField(max_length=221)

    def __str__(self):
        return self.title


class Blog(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to='blogs/')
    title = models.CharField(max_length=221)
    slug = models.SlugField(null=True, blank=True, unique_for_date='created_date', max_length=221)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    description = models.TextField()
    tags = models.ManyToManyField(Tag)
    views = models.IntegerField(default=0, editable=False)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    @property
    def get_absolute_url(self):
        url = reverse('blog:detail', kwargs={
            "year": self.created_date.year,
            "month": self.created_date.month,
            "day": self.created_date.day,
            "slug": self.slug
        })
        return url


# class BlogTag(models.Model):
#   blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
#  tag = models.ForeignKey(Tag, on_delete=models.CASCADE)


class SubBlog(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    title = models.CharField(max_length=211)
    description = models.TextField()
    image = models.ImageField(upload_to='blogs/', blank=True, null=True)
    contact = models.TextField()

    def __str__(self):
        return self.blog.title


def blog_pre_save(instance, sender, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)
    return instance


pre_save.connect(blog_pre_save, sender=Blog)

contact/models.py
from django.db import models


class Cantact(models.Model):
    full_name = models.CharField(max_length=221)
    email = models.EmailField(null=True, blank=True)
    subject = models.CharField(max_length=221)
    message = models.TextField()

    def __str__(self):
        return self.full_name

main/models.py
from django.db import models

from profiles.models import Profile


class Feedback(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    feedback = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.author}'s feedback"

profiles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profiles/', null=True, blank=True)
    bio = models.TextField(null=True, blank=True)
    position = models.CharField(max_length=211, null=True)

    def __str__(self):
        return str(self.id)

    @property
    def full_name(self):
        full_name = []
        if self.user.first_name:
            full_name.append(self.user.first_name)
        if self.user.last_name:
            full_name.append(self.user.last_name)
        full_name_str = " ".join(full_name)
        if full_name_str:
            return full_name_str
        return self.user.username


def user_post_save(instance, sender, created, *args, **kwargs):
    if created:
        obj = Profile.objects.create(user=instance)
        return obj
    return None


post_save.connect(user_post_save, sender=User)

contact/forms.py
from django import forms

from .models import Cantact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Cantact
        fields = ['full_name', 'email', 'subject', 'message']

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields['full_name'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Your name'
        })
        self.fields['email'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Your emil'
        })
        self.fields['subject'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Subject'
        })
        self.fields['message'].widget.attrs.update({
            'class': 'form-control',
            'placeholder': 'Your message'
        })

    def clean(self):
        data = self.cleaned_data
        data['full_name'] = data['full_name'].title()
        data['subject'] = data['subject'].capitalize()
        return data

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Tag, Category, Blog, SubBlog
from django.core.paginator import Paginator


def blog_list(request):
    blogs = Blog.objects.all().order_by('-id')
    q = request.GET.get('q')
    cat = request.GET.get('cat')
    tag = request.GET.get('tag')
    if q:
        blogs = blogs.filter(title__icontains=q)
    if tag:
        blogs = blogs.filter(category__title__exact=cat)
    if cat:
        blogs = blogs.filter(tags__title__exact=tag)
    paginator = Paginator(blogs, 3)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    ctx = {
        'object_list': page_obj,
    }

    return render(request, 'blog/blog.html', ctx)


def blog_detail(request, **kwargs):
    slug = kwargs.get('slug', None)
    year = kwargs.get('year', None)
    month = kwargs.get('month', None)
    day = kwargs.get('day', None)
    obj = get_object_or_404(Blog, slug=slug)
    categories = Category.objects.all()
    tags = Tag.objects.all()
    ctx = {
        'object': obj,
        'categories': categories,
        'tags': tags,
    }

    return render(request, 'blog/blog-single.html', ctx)

contact/views.py
from django.shortcuts import render, redirect
from django.contrib import messages

from .models import Cantact
from .forms import ContactForm


def contact(request):
    form = ContactForm()
    if request.method == "POST":
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your request successfully accepted')
            return redirect('.')

    ctx = {
        'form': form
    }

    return render(request, 'contact/contact.html', ctx)

main/views.py
from django.shortcuts import render
from django.core.paginator import Paginator
from blog.models import Blog
from .models import Feedback


def home(request):
    blogs = Blog.objects.order_by('-id')
    page_num = request.GET.get('page', 1)
    paginator = Paginator(blogs, 2)

    page_obj = paginator.page(page_num)

    ctx = {
        'object_list': page_obj,
        'latest_blog': blogs[:2]
    }
    return render(request, 'main/index.html', ctx)


def about(request):
    feedback = Feedback.objects.all()

    ctx = {
        'object_list': feedback
    }

    return render(request, 'main/about.html', ctx)

profiles/views.py
from django.shortcuts import render

# Create your views here.

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <section class="hero-wrap hero-wrap-2 js-fullheight"
             style="background-image: url('{% static 'images/bg_1.jpg' %}'); height: 386px; background-position: 50% 2325px;"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center"
                 style="height: 386px;">
                <div class="col-md-9 ftco-animate pb-5 text-center fadeInUp ftco-animated">
                    <h1 class="mb-3 bread">Blog Single</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main:home' %}">Home <i
                            class="ion-ios-arrow-forward"></i></a></span> <span class="mr-2"><a href="{% url 'blog:list' %}">Blog <i
                            class="ion-ios-arrow-forward"></i></a></span> <span>Blog Single <i
                            class="ion-ios-arrow-forward"></i></span></p>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section ftco-degree-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 ftco-animate">
                    <p class="mb-5">
                        <img src="{{ object.image.url }}" alt="" class="img-fluid">
                    </p>
                    <h2 class="mb-3">{{ object.title }}</h2>
                    <p>{{ object.description|safe }}</p>
                    {% for subblog in object.subblog_set.all %}
                        <h2 class="mb-3 mt-5">{{ forloop.counter|add:1 }}.{{ subblog.title }}</h2>
                        <p>{{ subblog.description|safe }}</p>

                        {% if subblog.image %}
                            <p class="mb-5">
                                <img src="{{ subblog.image.url }}" alt="" class="img-fluid">
                            </p>
                        {% endif %}

                        <p>{{ subblog.content|safe }}</p>
                    {% endfor %}

                    <div class="tag-widget post-tag-container mb-5 mt-5">
                        <div class="tagcloud">

                            {% for tag in object.tags.all %}
                            <a href="#" class="tag-cloud-link">{{ tag.title }}</a>
                            {% endfor %}

                        </div>
                    </div>
                    <div class="about-author d-flex p-4 bg-light">
                        <div class="bio mr-5">
                            {% if object.author.image %}
                            <img src="{{ object.author.image }}" alt="Image placeholder" class="img-fluid mb-4">
                            {% else %}
                                <img src="{% static 'images/profile.png' %}" style="width: 200px" alt="">
                            {% endif %}
                        </div>
                        <div class="desc">
                            <h3>{{ object.author.full_name }}</h3>
                            <p>{{ object.author.bio }}</p>
                        </div>
                    </div>
                    <div class="pt-5 mt-5">
                        <h3 class="mb-5">6 Comments</h3>
                        <ul class="comment-list">
                            <li class="comment">
                                <div class="vcard bio">
                                    <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                                </div>
                                <div class="comment-body">
                                    <h3>John Doe</h3>
                                    <div class="meta mb-3">November 13, 2019 at 2:21pm</div>
                                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum
                                        necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim
                                        sapiente
                                        iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                                </div>
                            </li>
                        </ul>

                        <div class="comment-form-wrap pt-5">
                            <h3 class="mb-5">Leave a comment</h3>
                            <form action="#" class="p-5 bg-light">
                                <div class="form-group">
                                    <label for="name">Name *</label>
                                    <input type="text" class="form-control" id="name">
                                </div>
                                <div class="form-group">
                                    <label for="email">Email *</label>
                                    <input type="email" class="form-control" id="email">
                                </div>
                                <div class="form-group">
                                    <label for="website">Website</label>
                                    <input type="url" class="form-control" id="website">
                                </div>
                                <div class="form-group">
                                    <label for="message">Message</label>
                                    <textarea name="" id="message" cols="30" rows="10" class="form-control"></textarea>
                                </div>
                                <div class="form-group">
                                    <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 sidebar pl-lg-5 ftco-animate">
                    <div class="sidebar-box">
                        <form action="{% url 'blog:list' %}" class="search-form">
                            <div class="form-group">
                                <span class="icon icon-search"></span>
                                <input type="text" name="q" class="form-control" placeholder="Type a keyword and hit enter">
                            </div>
                        </form>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <div class="categories">
                            <h3>Categories</h3>
                            {% for category in categories %}
                                <li><a href="{% url 'blog:list' %}?cat='{{ category.title }}'">{{ object.category.title }}<span class="ion-ios-arrow-forward"></span></a></li>
                            {% endfor %}
                        </div>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3>Recent Blog</h3>
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4"
                               style="background-image: url({% static 'images/image_1.jpg' %});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the
                                    blind texts</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> Nov. 14, 2019</a></div>
                                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4"
                               style="background-image: url({% static 'images/image_2.jpg' %});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the
                                    blind texts</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> Nov. 14, 2019</a></div>
                                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </div>
                        </div>
                        <div class="block-21 mb-4 d-flex">
                            <a class="blog-img mr-4"
                               style="background-image: url({% static 'images/image_3.jpg' %});"></a>
                            <div class="text">
                                <h3 class="heading"><a href="#">Even the all-powerful Pointing has no control about the
                                    blind texts</a></h3>
                                <div class="meta">
                                    <div><a href="#"><span class="icon-calendar"></span> Nov. 14, 2019</a></div>
                                    <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                    <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3>Tag Cloud</h3>
                        <div class="tagcloud">
                            <a href="#" class="tag-cloud-link">cat</a>
                            <a href="#" class="tag-cloud-link">abstract</a>
                            <a href="#" class="tag-cloud-link">people</a>
                            <a href="#" class="tag-cloud-link">person</a>
                            <a href="#" class="tag-cloud-link">model</a>
                            <a href="#" class="tag-cloud-link">delicious</a>
                            <a href="#" class="tag-cloud-link">desserts</a>
                            <a href="#" class="tag-cloud-link">drinks</a>
                        </div>
                    </div>
                    <div class="sidebar-box ftco-animate">
                        <h3>Paragraph</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                            necessitatibus
                            voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente consectetur
                            similique, inventore eos fugit cupiditate numquam!</p>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/contact/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="hero-wrap hero-wrap-2 js-fullheight"
             style="background-image: url('{% static 'images/bg_1.jpg' %}');"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-3 bread">Contact us</h1>
                    <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main:home' %}">Home <i
                            class="ion-ios-arrow-forward"></i></a></span> <span>About <i
                            class="ion-ios-arrow-forward"></i></span>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section contact-section">
        <div class="container">
            <div class="row d-flex mb-5 contact-info">
                <div class="col-md-12 mb-4">
                    <h2 class="h3">Contact Information</h2>
                </div>
                <div class="w-100"></div>
                <div class="col-md-3">
                    <p><span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016</p>
                </div>
                <div class="col-md-3">
                    <p><span>Phone:</span> <a href="tel://1234567920">+ 1235 2355 98</a></p>
                </div>
                <div class="col-md-3">
                    <p><span>Email:</span> <a
                            href="https://preview.colorlib.com/cdn-cgi/l/email-protection#afc6c1c9c0efd6c0dadddcc6dbca81ccc0c2"><span
                            class="__cf_email__"
                            data-cfemail="b7ded9d1d8f7ced8c2c5c4dec3d299d4d8da">[email&#160;protected]</span></a></p>
                </div>
                <div class="col-md-3">
                    <p><span>Website</span> <a href="#">yoursite.com</a></p>
                </div>
            </div>
            <div class="row block-9 no-gutters">
                <div class="col-lg-6 order-md-last d-flex">
                    <form method="post" class="bg-light p-4 p-md-5 contact-form">
                        {% csrf_token %}
                        <div class="form-group">
                            {{ form.full_name }}
                        </div>
                        <div class="form-group">
                            {{ form.email }}
                        </div>
                        <div class="form-group">
                            {{ form.subject }}
                        </div>
                        <div class="form-group">
                            {{ form.message }}
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 d-flex p-2">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2747.574723267417!2d69.32641747111688!3d41.325144578712695!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x38aef572e5842f55%3A0xa87fc261e04f75ea!2siSystem%20IT%20academy!5e0!3m2!1suz!2s!4v1685882226662!5m2!1suz!2s"
                            width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy"
                            referrerpolicy="no-referrer-when-downgrade"></iframe>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/loading.html
<div id="ftco-loader" class="show fullscreen">
    <svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"/>
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00"/>
    </svg>
</div>

templates/main/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<section class="hero-wrap hero-wrap-2 js-fullheight" style="background-image: url('{% static 'images/bg_1.jpg' %}');"
         data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text js-fullheight align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="{% url 'main:home' %}">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About <i class="ion-ios-arrow-forward"></i></span>
                </p>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section ftco-no-pt ftco-no-pb">
    <div class="container">
        <div class="row d-flex">
            <div class="col-md-6 d-flex">
                <div class="img img-video d-flex align-self-stretch align-items-center justify-content-center justify-content-md-end"
                     style="background-image:url({% static 'images/about.jpg' %});">
                    <a href="https://vimeo.com/45830194"
                       class="icon-video popup-vimeo d-flex justify-content-center align-items-center">
                        <span class="icon-play"></span>
                    </a>
                </div>
            </div>
            <div class="col-md-6 pl-md-5 py-md-5">
                <div class="row justify-content-start pt-3 pb-3">
                    <div class="col-md-12 heading-section ftco-animate">
                        <span class="subheading">Welcome to Readit</span>
                        <h2 class="mb-4">We give you the best articles you want.</h2>
                        <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</p>
                        <div class="tabulation-2 mt-4">
                            <ul class="nav nav-pills nav-fill d-md-flex d-block">
                                <li class="nav-item mb-md-0 mb-2">
                                    <a class="nav-link active py-2" data-toggle="tab" href="#home1">Our Mission</a>
                                </li>
                                <li class="nav-item px-lg-2 mb-md-0 mb-2">
                                    <a class="nav-link py-2" data-toggle="tab" href="#home2">Our Vision</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link py-2 mb-md-0 mb-2" data-toggle="tab" href="#home3">Our Value</a>
                                </li>
                            </ul>
                            <div class="tab-content bg-light rounded mt-2">
                                <div class="tab-pane container p-0 active" id="home1">
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                                        right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                                <div class="tab-pane container p-0 fade" id="home2">
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                                        right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                                <div class="tab-pane container p-0 fade" id="home3">
                                    <p>Far far away, behind the word mountains, far from the countries Vokalia and
                                        Consonantia, there live the blind texts. Separated they live in Bookmarksgrove
                                        right at the coast of the Semantics, a large language ocean.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="ftco-section testimony-section">
    <div class="container">
        <div class="row justify-content-center mb-5">
            <div class="col-md-7 text-center heading-section ftco-animate">
                <span class="subheading">Testimonial</span>
                <h2 class="mb-4">Happy Clients</h2>
            </div>
        </div>
        <div class="row ftco-animate">
            <div class="col-md-12">
                <div class="carousel-testimony owl-carousel ftco-owl">
                    {% for object in object_list %}
                        <div class="item">
                            <div class="testimony-wrap py-4">
                                <div class="text">
                                    <p class="mb-4">{{ object.feedback }}</p>
                                    <div class="d-flex align-items-center">
                                        {% if object.author.image %}
                                        <div class="user-img" style="background-image: url({{ object.author.image.url }})"></div>
                                        {% else %}
                                            <div class="user-img"
                                                 style="background-image: url({% static 'images/profile.png' %})"
                                        {% endif %}
                                        <div class="pl-3">
                                            <p class="name">{{ object.author }}</p>
                                            <span class="position">{{ object.author.position }}</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock %}

templates/navbar.html
<nav class="navbar px-md-0 navbar-expand-lg navbar-dark ftco_navbar bg-dark ftco-navbar-light" id="ftco-navbar">
    <div class="container">
        <a class="navbar-brand" href="../#">Read<i>it</i>.</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#ftco-nav"
                aria-controls="ftco-nav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="oi oi-menu"></span> Menu
        </button>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active"><a href="{% url 'main:home' %}" class="nav-link">Home</a></li>
                <li class="nav-item"><a href="{% url 'blog:list' %}" class="nav-link">Articles</a></li>
                <li class="nav-item"><a href="{% url 'main:about' %}" class="nav-link">Team</a></li>
                <li class="nav-item"><a href="{% url 'contact:contact' %}" class="nav-link">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>